### ISSUE TITLE
How do I pass configuration.

### ISSUE THREAD

**Issue by rifaideen** [cornernote/yii-embed-wordpress#4]
how can I set db configuration as like in normal yii application via config/main.php
I need help on this. my yii app running separately. I want to use its model in wordpress app. so give me an example.

**Comment by cornernote** [comment]
You won't have a config.php file, but you can still modify the yii app config...

You should have `YourPlugin::yiiInit()` method, inside you do like this:

``` php
Yii::app()->option = 'value';
```

**Comment by rifaideen** [comment]
Ok. I have another doubt. I have models for yii app. how do I use here?

**Comment by cornernote** [comment]
I'm on my phone so can't help until tomorrow. There is an example in the
docs of a plugin with a model.

**Comment by rifaideen** [comment]
It's ok thank you. my scenario is totally different than you shown in the
documentation.

Thanks and regards
_\- Rifaideen_

**Comment by cornernote** [comment]
If you have existing models, simply put them into your models directory and they should work (assuming that your models path is in your include path).

If you need further help please give more details on what is not working.
